logo: # add logo name
title: 人生如逆旅，我亦是行人
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Banner settings
video: mountains.mp4 # add banner video. Add your video file to the folder video
banner-title: # add banner title
banner-desc: # add banner description

# Author settings
author-pic: avatar.png # your photo
author-name: Fan Zou # your name
about-author: Software Engineer# about author
email: fan@zou.at # your email
phone: xyz # your pnone number
website: https://fan.zou.at # you website

# Social link
google_url:   http://mephifan.blogspot.com # add url link
twitter_url:  https://twitter.com/mephifan # add url link
instagram_url: https://www.instagram.com/mephifan/ # add url link
pinterest_url: https://www.pinterest.de/fanzou0662/# add url link
dribbble_url: https://mephifan.tumblr.com/ # add url link
facebook_url: https://www.facebook.com/mephifan # add url link

# Disqus
discus_identifier: mr-brown # add your discus identifier.  Not your username.  To get this, register your forum here with a unique ID: https://disqus.com/admin/create/

# Newsletter
mailchimp: # add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e

# Tracker
analytics:

# Paginate
paginate: 9
paginate_path: /page:num/

# Build settings
markdown: kramdown
plugins_dir:
  - jekyll-paginate
  - jekyll-sitemap
plugins:
  - jekyll-paginate
gems:
  - jekyll-paginate
  - jekyll-sitemap

include: [_pages]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
